[package]
name = "rust_mlp"
version = "0.1.0"
edition = "2021"

[build-dependencies]
cc = "1.2.30"

[dependencies]
rand = "0.8"
rand_pcg = "0.3"
flate2 = "1.0"
rayon = "1.8"
eframe = "0.31.1"
egui = "0.31.1"
libc = "0.2.174"
